epl_unnorm:
    flag_matrix: fmatrix
    flag_matrix_defs:
        fmatrix:
#            input_file: ['small_enterprise.P', 'large_enterprise.P']
#            rule: ['local_exploit_rules.P']
#            secmet_map_scores: [ 'cvss2time', 'cvss2effort']
            secmet_fix_cvss_score: [0, 1, 2, 3, 4, 5, 6,  7, 8, 9, 10]

    flags:
#        secmet_score_strategy: 'reliability'
        secmet_plot_intermediate_graphs: False
#        secmet_map_scores: 'cvss2time'
        #        input_file: single_host_1.P
        #        rule: local_exploit_rules.P