metf_ml:
  description: Run metf metric
  flags:
    secmet_plot_intermediate_graphs: False
#    secmet_fix_cvss_score: 1
#    secmet_map_scores: 'cvss2time'
    secmet_map_scores: 'cvss2effort'
    secmet_score_strategy: 'reliability'
    input_file: single_host_1.P
    rule: local_exploit_rules.P
    models_dir: /opt/projects/diss/py-mulval/data/models 
    rules_dir: /opt/projects/diss/py-mulval/data/rules 
    data_dir: /opt/projects/diss/py-mulval/data
    secmet_ag_path: AttackGraph.dot
  #   output_dir: /tmp/mulpy
  # vm_groups: